const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.NinePatch,
		C3.Plugins.Arr,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Tilemap.Exps.X,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Tilemap.Exps.Y,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.len,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Arr.Exps.Height,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Spawn
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{Solid: 0},
	{Wall: 0},
	{isTeleport: 0},
	{score: 0},
	{dir: 0},
	{powerActive: 0},
	{powerTimer: 0},
	{snapX: 0},
	{snapY: 0},
	{Bullet: 0},
	{Pacs: 0},
	{Keyboard: 0},
	{TunnelLeft: 0},
	{TunnelRight: 0},
	{isDangerous: 0},
	{Pellet: 0},
	{ScoreText: 0},
	{Audio: 0},
	{state: 0},
	{speed: 0},
	{nextDir: 0},
	{preferredDir: 0},
	{alternateDir: 0},
	{lastDir: 0},
	{frightened: 0},
	{eaten: 0},
	{frightenedTimer: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Blinky: 0},
	{houseTimer: 0},
	{targetY: 0},
	{Pinky: 0},
	{GhostHouseDoor: 0},
	{Pacz: 0},
	{Inky: 0},
	{scatterX: 0},
	{scatterY: 0},
	{Clyde: 0},
	{TextBox: 0},
	{NameText: 0},
	{DialogueText: 0},
	{Continue: 0},
	{DialogueArray: 0},
	{currentEffect: 0},
	{PowerPellet: 0},
	{Fade: 0},
	{Flashing: 0},
	{ButtonUp: 0},
	{ButtonDown: 0},
	{ButtonLeft: 0},
	{ButtonRight: 0},
	{Touch: 0},
	{TitleText: 0},
	{ButtonNewGame: 0},
	{ButtonContinue: 0},
	{ButtonCredits: 0},
	{ButtonExit: 0},
	{MenuText: 0},
	{Browser: 0},
	{isUsed: 0},
	{PelletMarker: 0},
	{Strawberry: 0},
	{gameEnding: 0},
	{isDying: 0},
	{pelletsEaten: 0},
	{eatenPelletsPositions: 0},
	{playerLives: 0},
	{gameOver: 0},
	{dialogueIndex: 0},
	{isTyping: 0},
	{currentCharIndex: 0},
	{typingSpeed: 0},
	{typingTimer: 0},
	{fullDialogue: 0},
	{levelStartTimer: 0},
	{pelletsEaten2: 0},
	{eatenPelletsPositions2: 0},
	{dialogueIndex2: 0},
	{isTyping2: 0},
	{currentCharIndex2: 0},
	{typingSpeed2: 0},
	{typingTimer2: 0},
	{fullDialogue2: 0},
	{currentLevel: 0},
	{dialogueIndex3: 0},
	{isTyping3: 0},
	{currentCharIndex3: 0},
	{typingSpeed3: 0},
	{typingTimer3: 0},
	{fullDialogue3: 0},
	{dialogueIndex4: 0},
	{isTyping4: 0},
	{currentCharIndex4: 0},
	{typingSpeed4: 0},
	{typingTimer4: 0},
	{fullDialogue4: 0},
	{pelletsEaten3: 0},
	{eatenPelletsPositions3: 0},
	{dialogueIndex5: 0},
	{isTyping5: 0},
	{currentCharIndex5: 0},
	{typingSpeed5: 0},
	{typingTimer5: 0},
	{fullDialogue5: 0},
	{dialogueIndex6: 0},
	{isTyping6: 0},
	{currentCharIndex6: 0},
	{typingSpeed6: 0},
	{typingTimer6: 0},
	{fullDialogue6: 0},
	{strawberryTimer: 0},
	{strawberrySpawnDelay: 0},
	{strawberryLifetime: 0},
	{strawberryActive: 0},
	{strawberryEffectTimer: 0},
	{strawberryActiveEffect: 0},
	{pelletsEaten4: 0},
	{eatenPelletsPositions4: 0},
	{dialogueIndex7: 0},
	{isTyping7: 0},
	{currentCharIndex7: 0},
	{typingSpeed7: 0},
	{typingTimer7: 0},
	{fullDialogue7: 0},
	{pelletsEaten5: 0},
	{eatenPelletsPositions5: 0},
	{dangerousPelletTimer: 0},
	{dangerousPelletCount: 0}
];

self.InstanceType = {
	BG: class extends self.ITiledBackgroundInstance {},
	Wall: class extends self.ITilemapInstance {},
	Pacs: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TunnelLeft: class extends self.ISpriteInstance {},
	TunnelRight: class extends self.ISpriteInstance {},
	Pellet: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	Audio: class extends self.IInstance {},
	Blinky: class extends self.ISpriteInstance {},
	Pinky: class extends self.ISpriteInstance {},
	GhostHouseDoor: class extends self.ISpriteInstance {},
	Pacz: class extends self.ISpriteInstance {},
	Inky: class extends self.ISpriteInstance {},
	Clyde: class extends self.ISpriteInstance {},
	TextBox: class extends self.I9PatchInstance {},
	NameText: class extends self.ITextInstance {},
	DialogueText: class extends self.ITextInstance {},
	Continue: class extends self.ISpriteInstance {},
	DialogueArray: class extends self.IArrayInstance {},
	PowerPellet: class extends self.ISpriteInstance {},
	Flashing: class extends self.ISpriteInstance {},
	ButtonUp: class extends self.ISpriteInstance {},
	ButtonDown: class extends self.ISpriteInstance {},
	ButtonLeft: class extends self.ISpriteInstance {},
	ButtonRight: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TitleText: class extends self.ITextInstance {},
	ButtonNewGame: class extends self.ISpriteInstance {},
	ButtonContinue: class extends self.ISpriteInstance {},
	ButtonCredits: class extends self.ISpriteInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	MenuText: class extends self.ITextInstance {},
	Browser: class extends self.IInstance {},
	PelletMarker: class extends self.ISpriteInstance {},
	Strawberry: class extends self.ISpriteInstance {}
}